name: Download and Merge Bugzilla Data

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:

jobs:
  download-and-merge-bugzilla-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Update paths to store files in the 'data/' directory
    - name: Download Bugzilla data (medium impact)
      run: |
        curl -o data/bugzilla-data-medium.json "https://bugzilla.mozilla.org/rest/bug?include_fields=id,summary,status,resolution,component,creation_time,last_change_time,keywords,priority,severity,op_sys&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&f1=cf_performance_impact&limit=0&o1=equals&v1=medium"

    - name: Download Bugzilla data (low impact)
      run: |
        curl -o data/bugzilla-data-low.json "https://bugzilla.mozilla.org/rest/bug?include_fields=id,summary,status,resolution,component,creation_time,last_change_time,keywords,priority,severity,op_sys&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&f1=cf_performance_impact&limit=0&o1=equals&v1=low"

    - name: Download Bugzilla data (high impact)
      run: |
        curl -o data/bugzilla-data-high.json "https://bugzilla.mozilla.org/rest/bug?include_fields=id,summary,status,resolution,component,creation_time,last_change_time,keywords,priority,severity,op_sys&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&f1=cf_performance_impact&limit=0&o1=equals&v1=high"

    - name: Download Bugzilla data (untriaged)
      run: |
        curl -o data/bugzilla-data-untriaged.json "https://bugzilla.mozilla.org/rest/bug?include_fields=id,summary,status,resolution,component,creation_time,last_change_time,keywords,priority,severity,op_sys&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&f1=cf_performance_impact&limit=0&o1=equals&v1=%3F"

    - name: Download Bugzilla data (needinfo)
      run: |
        curl -o data/bugzilla-data-needinfo.json "https://bugzilla.mozilla.org/rest/bug?include_fields=id,summary,status,resolution,component,creation_time,last_change_time,keywords,priority,severity,op_sys&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&f1=cf_performance_impact&limit=0&o1=equals&v1=pending-needinfo"

    # Merge JSON files stored in the 'data/' directory
    - name: Merge JSON files
      run: |
        jq -n '{high: $high[], medium: $medium[], low: $low[], untriaged: $untriaged[], needinfo: $needinfo[]}' \
          --slurpfile high data/bugzilla-data-high.json \
          --slurpfile medium data/bugzilla-data-medium.json \
          --slurpfile low data/bugzilla-data-low.json \
          --slurpfile untriaged data/bugzilla-data-untriaged.json \
          --slurpfile needinfo data/bugzilla-data-needinfo.json > data/bugzilla-data-all.json

    # Commit and push changes for files in 'data/' directory
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/bugzilla-data-medium.json data/bugzilla-data-low.json data/bugzilla-data-high.json data/bugzilla-data-untriaged.json data/bugzilla-data-needinfo.json data/bugzilla-data-all.json
        git commit -m "Update Bugzilla data"
        git push
